import java.io.*;
import java.util.Scanner;

public class Main {
    private static final String[] LINES = new String[]{
            "\"<<BMK>>A001RFLGW1       \",\"E       0.0 \",\"BOOL      \",\"(A1) Spiegeln Folgenanwahl W1                                                   \"",
            "\"<<BMK>>A002RFLGW2       \",\"E       0.1 \",\"BOOL      \",\"(A2) Spiegeln Folgenanwahl W2                                                   \"",
            "\"<<BMK>>A003RFLGW4       \",\"E       0.2 \",\"BOOL      \",\"(A3) Spiegeln Folgenanwahl W4                                                   \"",
            "\"<<BMK>>A004RFLGW8       \",\"E       0.3 \",\"BOOL      \",\"(A4) Spiegeln Folgenanwahl W8                                                   \"",
            "\"<<BMK>>A005RFLGW16      \",\"E       0.4 \",\"BOOL      \",\"(A5) Spiegeln Folgenanwahl W16                                                  \"",
            "\"<<BMK>>A006RFLGW32      \",\"E       0.5 \",\"BOOL      \",\"(A6) Spiegeln Folgenanwahl W32                                                  \"",
            "\"<<BMK>>A007RFLGW64      \",\"E       0.6 \",\"BOOL      \",\"(A7) Spiegeln Folgenanwahl W64                                                  \"",
            "\"<<BMK>>A008RFLGW128     \",\"E       0.7 \",\"BOOL      \",\"(A8) Spiegeln Folgenanwahl W128                                                 \"",
            "\"<<BMK>>A009BEREIT       \",\"E       1.0 \",\"BOOL      \",\"(A9) Bereit                                                                     \"",
            "\"<<BMK>>A010RK100        \",\"E       1.1 \",\"BOOL      \",\"(A10) Freigabe Stellglieder                                                     \"",
            "\"<<BMK>>A011RK23         \",\"E       1.2 \",\"BOOL      \",\"(A11) Single Step/Hand                                                          \"",
            "\"<<BMK>>A012RK9          \",\"E       1.3 \",\"BOOL      \",\"(A12) Automatik                                                                 \"",
            "\"<<BMK>>A013SN           \",\"E       1.4 \",\"BOOL      \",\"(A13) Not-Aus am Roboter                                                        \"",
            "\"<<BMK>>A014LPKT         \",\"E       1.5 \",\"BOOL      \",\"(A14) Letzter Punkt erreicht                                                    \"",
            "\"<<BMK>>A015PF0          \",\"E       1.6 \",\"BOOL      \",\"(A15) Roboter ist im Punkt 0                                                    \"",
            "\"<<BMK>>A016SAK          \",\"E       1.7 \",\"BOOL      \",\"(A16) Roboter ist auf der Bahn                                                  \"",
            "\"<<BMK>>A017WART1        \",\"E       2.0 \",\"BOOL      \",\"(A17) Roboter in Wartungsstellung                                               \"",
            "\"<<BMK>>A018WARTBE       \",\"E       2.1 \",\"BOOL      \",\"(A18) Roboter in Wartungsbereich                                                \"",
            "\"<<BMK>>A019WART_FAHR    \",\"E       2.2 \",\"BOOL      \",\"(A19) Warte auf Fahrbedingung                                                   \"",
            "\"<<BMK>>A020WART_SPS     \",\"E       2.3 \",\"BOOL      \",\"(A20) Warte auf SPS-Rueckmeldung                                                \"",
            "\"<<BMK>>A021WART_VER     \",\"E       2.4 \",\"BOOL      \",\"(A21) Warte auf Roboterverriegelung                                             \"",
            "\"<<BMK>>A022FLGWAKTIV    \",\"E       2.5 \",\"BOOL      \",\"(A22) Folgenwiederholung aktiv                                                  \"",
            "\"<<BMK>>A023BG           \",\"E       2.6 \",\"BOOL      \",\"(A23) Schutzgitter gesperrt                                                     \"",
            "\"<<BMK>>A024BEW          \",\"E       2.7 \",\"BOOL      \",\"(A24) Roboter ist in Bewegung                                                   \"",
            "\"<<BMK>>A025MEDEINK      \",\"E       3.0 \",\"BOOL      \",\"(A25) Medien sind eingeschaltet                                                 \"",
            "\"<<BMK>>A026FELDWARN     \",\"E       3.1 \",\"BOOL      \",\"(A26) Feldbus Quality / Warnmeldung                                             \"",
            "\"<<BMK>>A027MASTE_IO     \",\"E       3.2 \",\"BOOL      \",\"(A27) Roboter Master i.O.                                                       \"",
            "\"<<BMK>>A028/100OVER     \",\"E       3.3 \",\"BOOL      \",\"(A28) Roboter nicht auf 100% Override                                           \"",
            "\"<<BMK>>A029ANFENERGIK   \",\"E       3.4 \",\"BOOL      \",\"(A29) Energiesparmodus                                                          \"",
            "\"<<BMK>>A030AB_ERLAUBT   \",\"E       3.5 \",\"BOOL      \",\"(A30) Abschaltung erlaubt                                                       \"",
            "\"<<BMK>>A031AR_BEENDET   \",\"E       3.6 \",\"BOOL      \",\"(A31) Archivieren beendet                                                       \"",
            "\"<<BMK>>A032PUFFER_WARN  \",\"E       3.7 \",\"BOOL      \",\"(A32) Warnung Pufferbatterie                                                    \"",
            "\"<<BMK>>A033ABE_W1       \",\"E       4.0 \",\"BOOL      \",\"(A33) Arbeitsfertigmeldung W1                                                   \"",
            "\"<<BMK>>A034ABE_W2       \",\"E       4.1 \",\"BOOL      \",\"(A34) Arbeitsfertigmeldung W2                                                   \"",
            "\"<<BMK>>A035ABE_W4       \",\"E       4.2 \",\"BOOL      \",\"(A35) Arbeitsfertigmeldung W4                                                   \"",
            "\"<<BMK>>A036ABE_W8       \",\"E       4.3 \",\"BOOL      \",\"(A36) Arbeitsfertigmeldung W8                                                   \"",
            "\"<<BMK>>A037_A_TYP_W1    \",\"E       4.4 \",\"BOOL      \",\"(A37) Typinfo W1 von Roboter                                                    \"",
            "\"<<BMK>>A038_A_TYP_W2    \",\"E       4.5 \",\"BOOL      \",\"(A38) Typinfo W2 von Roboter                                                    \"",
            "\"<<BMK>>A039_A_TYP_W4    \",\"E       4.6 \",\"BOOL      \",\"(A39) Typinfo W4 von Roboter                                                    \"",
            "\"<<BMK>>A040_A_TYP_W8    \",\"E       4.7 \",\"BOOL      \",\"(A40) Typinfo W8 von Roboter                                                    \"",
            "\"<<BMK>>A041V1           \",\"E       5.0 \",\"BOOL      \",\"(A41) Roboterverriegelung 1 Rob > Rob                                           \"",
            "\"<<BMK>>A042V2           \",\"E       5.1 \",\"BOOL      \",\"(A42) Roboterverriegelung 2 Rob > Rob                                           \"",
            "\"<<BMK>>A043V3           \",\"E       5.2 \",\"BOOL      \",\"(A43) Roboterverriegelung 3 Rob > Rob                                           \"",
            "\"<<BMK>>A044V4           \",\"E       5.3 \",\"BOOL      \",\"(A44) Roboterverriegelung 4 Rob > Rob                                           \"",
            "\"<<BMK>>A045V5           \",\"E       5.4 \",\"BOOL      \",\"(A45) Roboterverriegelung 5 Rob > Rob                                           \"",
            "\"<<BMK>>A046V6           \",\"E       5.5 \",\"BOOL      \",\"(A46) Roboterverriegelung 6 Rob > Rob                                           \"",
            "\"<<BMK>>A047V7           \",\"E       5.6 \",\"BOOL      \",\"(A47) Roboterverriegelung 7 Rob> Rob                                            \"",
            "\"<<BMK>>A048V8           \",\"E       5.7 \",\"BOOL      \",\"(A48) Roboterverriegelung 8 Rob > Rob                                           \"",
            "\"<<BMK>>A049V9           \",\"E       6.0 \",\"BOOL      \",\"(A49) Roboterverriegelung 9 Rob > Rob                                           \"",
            "\"<<BMK>>A050V10          \",\"E       6.1 \",\"BOOL      \",\"(A50) Roboterverriegelung 10 Rob > Rob                                          \"",
            "\"<<BMK>>A051V11          \",\"E       6.2 \",\"BOOL      \",\"(A51) Roboterverriegelung 11 Rob > Rob                                          \"",
            "\"<<BMK>>A052V12          \",\"E       6.3 \",\"BOOL      \",\"(A52) Roboterverriegelung 12 Rob > Rob                                          \"",
            "\"<<BMK>>A053V13          \",\"E       6.4 \",\"BOOL      \",\"(A53) Roboterverriegelung 13 Rob > Rob                                          \"",
            "\"<<BMK>>A054V14          \",\"E       6.5 \",\"BOOL      \",\"(A54) Roboterverriegelung 14 Rob > Rob                                          \"",
            "\"<<BMK>>A055V15          \",\"E       6.6 \",\"BOOL      \",\"(A55) Roboterverriegelung 15 Rob > Rob                                          \"",
            "\"<<BMK>>A056V16          \",\"E       6.7 \",\"BOOL      \",\"(A56) Roboterverriegelung 16 Rob > Rob                                          \"",
            "\"<<BMK>>A057PF24         \",\"E       7.0 \",\"BOOL      \",\"(A57) Werkzeugfreigabe 24 Rob > Anlage                                          \"",
            "\"<<BMK>>A058PF23         \",\"E       7.1 \",\"BOOL      \",\"(A58) Werkzeugfreigabe 23 Rob > Anlage                                          \"",
            "\"<<BMK>>A059PF22         \",\"E       7.2 \",\"BOOL      \",\"(A59) Werkzeugfreigabe 22 Rob > Anlage                                          \"",
            "\"<<BMK>>A060PF21         \",\"E       7.3 \",\"BOOL      \",\"(A60) Werkzeugfreigabe 21 Rob > Anlage                                          \"",
            "\"<<BMK>>A061PF20         \",\"E       7.4 \",\"BOOL      \",\"(A61) Werkzeugfreigabe 20 Rob > Anlage                                          \"",
            "\"<<BMK>>A062PF19         \",\"E       7.5 \",\"BOOL      \",\"(A62) Werkzeugfreigabe 19 Rob > Anlage                                          \"",
            "\"<<BMK>>A063PF18         \",\"E       7.6 \",\"BOOL      \",\"(A63) Werkzeugfreigabe 18 Rob > Anlage                                          \"",
            "\"<<BMK>>A064PF17         \",\"E       7.7 \",\"BOOL      \",\"(A64) Werkzeugfreigabe 17 Rob > Anlage                                          \"",
            "\"<<BMK>>A065PF16         \",\"E       8.0 \",\"BOOL      \",\"(A65) Werkzeugfreigabe 16 Rob > Anlage                                          \"",
            "\"<<BMK>>A066PF15         \",\"E       8.1 \",\"BOOL      \",\"(A66) Werkzeugfreigabe 15 Rob > Anlage                                          \"",
            "\"<<BMK>>A067PF14         \",\"E       8.2 \",\"BOOL      \",\"(A67) Werkzeugfreigabe 14 Rob > Anlage                                          \"",
            "\"<<BMK>>A068PF13         \",\"E       8.3 \",\"BOOL      \",\"(A68) Werkzeugfreigabe 13 Rob > Anlage                                          \"",
            "\"<<BMK>>A069PF12         \",\"E       8.4 \",\"BOOL      \",\"(A69) Werkzeugfreigabe 12 Rob > Anlage                                          \"",
            "\"<<BMK>>A070PF11         \",\"E       8.5 \",\"BOOL      \",\"(A70) Werkzeugfreigabe 11 Rob > Anlage                                          \"",
            "\"<<BMK>>A071PF10         \",\"E       8.6 \",\"BOOL      \",\"(A71) Werkzeugfreigabe 10 Rob > Anlage                                          \"",
            "\"<<BMK>>A072PF9          \",\"E       8.7 \",\"BOOL      \",\"(A72) Werkzeugfreigabe 9 Rob > Anlage                                           \"",
            "\"<<BMK>>A073PF8          \",\"E       9.0 \",\"BOOL      \",\"(A73) Werkzeugfreigabe 8 Rob > Anlage                                           \"",
            "\"<<BMK>>A074PF7          \",\"E       9.1 \",\"BOOL      \",\"(A74) Werkzeugfreigabe 7 Rob > Anlage                                           \"",
            "\"<<BMK>>A075PF6          \",\"E       9.2 \",\"BOOL      \",\"(A75) Werkzeugfreigabe 6 Rob > Anlage                                           \"",
            "\"<<BMK>>A076PF5          \",\"E       9.3 \",\"BOOL      \",\"(A76) Werkzeugfreigabe 5 Rob > Anlage                                           \"",
            "\"<<BMK>>A077PF4          \",\"E       9.4 \",\"BOOL      \",\"(A77) Werkzeugfreigabe 4 Rob > Anlage                                           \"",
            "\"<<BMK>>A078PF3          \",\"E       9.5 \",\"BOOL      \",\"(A78) Werkzeugfreigabe 3 Rob > Anlage                                           \"",
            "\"<<BMK>>A079PF2          \",\"E       9.6 \",\"BOOL      \",\"(A79) Werkzeugfreigabe 2 Rob > Anlage                                           \"",
            "\"<<BMK>>A080PF1          \",\"E       9.7 \",\"BOOL      \",\"(A80) Werkzeugfreigabe 1 Rob > Anlage                                           \"",
            "\"<<BMK>>A081AF_VER1      \",\"E      10.0 \",\"BOOL      \",\"(A81) Anford. Verriegelung 1 Rob > Rob                                          \"",
            "\"<<BMK>>A082AF_VER2      \",\"E      10.1 \",\"BOOL      \",\"(A82) Anford. Verriegelung 2 Rob > Rob                                          \"",
            "\"<<BMK>>A083AF_VER3      \",\"E      10.2 \",\"BOOL      \",\"(A83) Anford. Verriegelung 3 Rob > Rob                                          \"",
            "\"<<BMK>>A084AF_VER4      \",\"E      10.3 \",\"BOOL      \",\"(A84) Anford. Verriegelung 4 Rob > Rob                                          \"",
            "\"<<BMK>>A085AF_VER5      \",\"E      10.4 \",\"BOOL      \",\"(A85) Anford. Verriegelung 5 Rob > Rob                                          \"",
            "\"<<BMK>>A086AF_VER6      \",\"E      10.5 \",\"BOOL      \",\"(A86) Anford. Verriegelung 6 Rob > Rob                                          \"",
            "\"<<BMK>>A087AF_VER7      \",\"E      10.6 \",\"BOOL      \",\"(A87) Anford. Verriegelung 7 Rob > Rob                                          \"",
            "\"<<BMK>>A088AF_VER8      \",\"E      10.7 \",\"BOOL      \",\"(A88) Anford. Verriegelung 8 Rob > Rob                                          \"",
            "\"<<BMK>>A089AF_VER9      \",\"E      11.0 \",\"BOOL      \",\"(A89) Anford. Verriegelung 9 Rob > Rob                                          \"",
            "\"<<BMK>>A090AF_VER10     \",\"E      11.1 \",\"BOOL      \",\"(A90) Anford. Verriegelung 10 Rob > Rob                                         \"",
            "\"<<BMK>>A091AF_VER11     \",\"E      11.2 \",\"BOOL      \",\"(A91) Anford. Verriegelung 11 Rob > Rob                                         \"",
            "\"<<BMK>>A092AF_VER12     \",\"E      11.3 \",\"BOOL      \",\"(A92) Anford. Verriegelung 12 Rob > Rob                                         \"",
            "\"<<BMK>>A093AF_VER13     \",\"E      11.4 \",\"BOOL      \",\"(A93) Anford. Verriegelung 13 Rob > Rob                                         \"",
            "\"<<BMK>>A094AF_VER14     \",\"E      11.5 \",\"BOOL      \",\"(A94) Anford. Verriegelung 14 Rob > Rob                                         \"",
            "\"<<BMK>>A095AF_VER15     \",\"E      11.6 \",\"BOOL      \",\"(A95) Anford. Verriegelung 15 Rob > Rob                                         \"",
            "\"<<BMK>>A096AF_VER16     \",\"E      11.7 \",\"BOOL      \",\"(A96) Anford. Verriegelung 16 Rob > Rob                                         \"",
            "\"<<BMK>>A097PRO_W1       \",\"E      12.0 \",\"BOOL      \",\"(A97) Prozesspkt/geraete-Nr. W1                                                 \"",
            "\"<<BMK>>A098PRO_W2       \",\"E      12.1 \",\"BOOL      \",\"(A98) Prozesspkt/geraete-Nr. W2                                                 \"",
            "\"<<BMK>>A099PRO_W4       \",\"E      12.2 \",\"BOOL      \",\"(A99) Prozesspkt/geraete-Nr. W4                                                 \"",
            "\"<<BMK>>A100PRO_W8       \",\"E      12.3 \",\"BOOL      \",\"(A100) Prozesspkt/geraete-Nr. W8                                                \"",
            "\"<<BMK>>A101PRO_W16      \",\"E      12.4 \",\"BOOL      \",\"(A101) Prozesspkt/geraete-Nr. W16                                               \"",
            "\"<<BMK>>A102PRO_W32      \",\"E      12.5 \",\"BOOL      \",\"(A102) Prozesspkt/geraete-Nr. W32                                               \"",
            "\"<<BMK>>A103PRO_W64      \",\"E      12.6 \",\"BOOL      \",\"(A103) Prozesspkt/geraete-Nr. W64                                               \"",
            "\"<<BMK>>A104PRO_W128     \",\"E      12.7 \",\"BOOL      \",\"(A104) Prozesspkt/geraete-Nr. W128                                              \"",
            "\"<<BMK>>A105PRO_W256     \",\"E      13.0 \",\"BOOL      \",\"(A105) Prozesspkt/geraete-Nr. W256                                              \"",
            "\"<<BMK>>A106PRO_W512     \",\"E      13.1 \",\"BOOL      \",\"(A106) Prozesspkt/geraete-Nr. W512                                              \"",
            "\"<<BMK>>A107PRO_W1024    \",\"E      13.2 \",\"BOOL      \",\"(A107) Prozesspkt/geraete-Nr. W1024                                             \"",
            "\"<<BMK>>A108PRO_W2048    \",\"E      13.3 \",\"BOOL      \",\"(A108) Prozesspkt/geraete-Nr. W2048                                             \"",
            "\"<<BMK>>A109PRO_W4096    \",\"E      13.4 \",\"BOOL      \",\"(A109) Prozesspkt/geraete-Nr. W4096                                             \"",
            "\"<<BMK>>A110PRO_W8192    \",\"E      13.5 \",\"BOOL      \",\"(A110) Prozesspkt/geraete-Nr. W8192                                             \"",
            "\"<<BMK>>A111PRO_W16384   \",\"E      13.6 \",\"BOOL      \",\"(A111) Prozesspkt/geraete-Nr. W16384                                            \"",
            "\"<<BMK>>A112PRO_W32768   \",\"E      13.7 \",\"BOOL      \",\"(A112) Prozesspkt/geraete-Nr. W32768                                            \"",
            "\"<<BMK>>A113RES          \",\"E      14.0 \",\"BOOL      \",\"(A113) Reserviert                                                               \"",
            "\"<<BMK>>A114RES          \",\"E      14.1 \",\"BOOL      \",\"(A114) Reserviert                                                               \"",
            "\"<<BMK>>A115RES          \",\"E      14.2 \",\"BOOL      \",\"(A115) Reserviert                                                               \"",
            "\"<<BMK>>A116RES          \",\"E      14.3 \",\"BOOL      \",\"(A116) Reserviert                                                               \"",
            "\"<<BMK>>A117RES          \",\"E      14.4 \",\"BOOL      \",\"(A117) Reserviert                                                               \"",
            "\"<<BMK>>A118RES          \",\"E      14.5 \",\"BOOL      \",\"(A118) Reserviert                                                               \"",
            "\"<<BMK>>A119RES          \",\"E      14.6 \",\"BOOL      \",\"(A119) Reserviert                                                               \"",
            "\"<<BMK>>A120RES          \",\"E      14.7 \",\"BOOL      \",\"(A120) Reserviert                                                               \"",
            "\"<<BMK>>A121RES          \",\"E      15.0 \",\"BOOL      \",\"(A121) Reserviert                                                               \"",
            "\"<<BMK>>A122RES          \",\"E      15.1 \",\"BOOL      \",\"(A122) Reserviert                                                               \"",
            "\"<<BMK>>A123RES          \",\"E      15.2 \",\"BOOL      \",\"(A123) Reserviert                                                               \"",
            "\"<<BMK>>A124RES          \",\"E      15.3 \",\"BOOL      \",\"(A124) Reserviert                                                               \"",
            "\"<<BMK>>A125RES          \",\"E      15.4 \",\"BOOL      \",\"(A125) Reserviert                                                               \"",
            "\"<<BMK>>A126RES          \",\"E      15.5 \",\"BOOL      \",\"(A126) Reserviert                                                               \"",
            "\"<<BMK>>A127RES          \",\"E      15.6 \",\"BOOL      \",\"(A127) Reserviert                                                               \"",
            "\"<<BMK>>A128RES          \",\"E      15.7 \",\"BOOL      \",\"(A128) Reserviert                                                               \"",
            "\"<<BMK>>A129RES          \",\"E      16.0 \",\"BOOL      \",\"(A129) Reserviert                                                               \"",
            "\"<<BMK>>A130RES          \",\"E      16.1 \",\"BOOL      \",\"(A130) Reserviert                                                               \"",
            "\"<<BMK>>A131RES          \",\"E      16.2 \",\"BOOL      \",\"(A131) Reserviert                                                               \"",
            "\"<<BMK>>A132RES          \",\"E      16.3 \",\"BOOL      \",\"(A132) Reserviert                                                               \"",
            "\"<<BMK>>A133RES          \",\"E      16.4 \",\"BOOL      \",\"(A133) Reserviert                                                               \"",
            "\"<<BMK>>A134RES          \",\"E      16.5 \",\"BOOL      \",\"(A134) Reserviert                                                               \"",
            "\"<<BMK>>A135RES          \",\"E      16.6 \",\"BOOL      \",\"(A135) Reserviert                                                               \"",
            "\"<<BMK>>A136RES          \",\"E      16.7 \",\"BOOL      \",\"(A136) Reserviert                                                               \"",
            "\"<<BMK>>A137RES          \",\"E      17.0 \",\"BOOL      \",\"(A137) Reserviert                                                               \"",
            "\"<<BMK>>A138RES          \",\"E      17.1 \",\"BOOL      \",\"(A138) Reserviert                                                               \"",
            "\"<<BMK>>A139RES          \",\"E      17.2 \",\"BOOL      \",\"(A139) Reserviert                                                               \"",
            "\"<<BMK>>A140RES          \",\"E      17.3 \",\"BOOL      \",\"(A140) Reserviert                                                               \"",
            "\"<<BMK>>A141RES          \",\"E      17.4 \",\"BOOL      \",\"(A141) Reserviert                                                               \"",
            "\"<<BMK>>A142RES          \",\"E      17.5 \",\"BOOL      \",\"(A142) Reserviert                                                               \"",
            "\"<<BMK>>A143RES          \",\"E      17.6 \",\"BOOL      \",\"(A143) Reserviert                                                               \"",
            "\"<<BMK>>A144RES          \",\"E      17.7 \",\"BOOL      \",\"(A144) Reserviert                                                               \"",
            "\"<<BMK>>A145RES          \",\"E      18.0 \",\"BOOL      \",\"(A145) Reserviert                                                               \"",
            "\"<<BMK>>A146RES          \",\"E      18.1 \",\"BOOL      \",\"(A146) Reserviert                                                               \"",
            "\"<<BMK>>A147RES          \",\"E      18.2 \",\"BOOL      \",\"(A147) Reserviert                                                               \"",
            "\"<<BMK>>A148RES          \",\"E      18.3 \",\"BOOL      \",\"(A148) Reserviert                                                               \"",
            "\"<<BMK>>A149RES          \",\"E      18.4 \",\"BOOL      \",\"(A149) Reserviert                                                               \"",
            "\"<<BMK>>A150RES          \",\"E      18.5 \",\"BOOL      \",\"(A150) Reserviert                                                               \"",
            "\"<<BMK>>A151RES          \",\"E      18.6 \",\"BOOL      \",\"(A151) Reserviert                                                               \"",
            "\"<<BMK>>A152RES          \",\"E      18.7 \",\"BOOL      \",\"(A152) Reserviert                                                               \"",
            "\"<<BMK>>A153RES          \",\"E      19.0 \",\"BOOL      \",\"(A153) Reserviert                                                               \"",
            "\"<<BMK>>A154RES          \",\"E      19.1 \",\"BOOL      \",\"(A154) Reserviert                                                               \"",
            "\"<<BMK>>A155RES          \",\"E      19.2 \",\"BOOL      \",\"(A155) Reserviert                                                               \"",
            "\"<<BMK>>A156RES          \",\"E      19.3 \",\"BOOL      \",\"(A156) Reserviert                                                               \"",
            "\"<<BMK>>A157RES          \",\"E      19.4 \",\"BOOL      \",\"(A157) Reserviert                                                               \"",
            "\"<<BMK>>A158RES          \",\"E      19.5 \",\"BOOL      \",\"(A158) Reserviert                                                               \"",
            "\"<<BMK>>A159RES          \",\"E      19.6 \",\"BOOL      \",\"(A159) Reserviert                                                               \"",
            "\"<<BMK>>A160RES          \",\"E      19.7 \",\"BOOL      \",\"(A160) Reserviert                                                               \"",
            "\"<<BMK>>A161RES          \",\"E      20.0 \",\"BOOL      \",\"(A161) Reserviert                                                               \"",
            "\"<<BMK>>A162RES          \",\"E      20.1 \",\"BOOL      \",\"(A162) Reserviert                                                               \"",
            "\"<<BMK>>A163RES          \",\"E      20.2 \",\"BOOL      \",\"(A163) Reserviert                                                               \"",
            "\"<<BMK>>A164RES          \",\"E      20.3 \",\"BOOL      \",\"(A164) Reserviert                                                               \"",
            "\"<<BMK>>A165RES          \",\"E      20.4 \",\"BOOL      \",\"(A165) Reserviert                                                               \"",
            "\"<<BMK>>A166RES          \",\"E      20.5 \",\"BOOL      \",\"(A166) Reserviert                                                               \"",
            "\"<<BMK>>A167RES          \",\"E      20.6 \",\"BOOL      \",\"(A167) Reserviert                                                               \"",
            "\"<<BMK>>A168RES          \",\"E      20.7 \",\"BOOL      \",\"(A168) Reserviert                                                               \"",
            "\"<<BMK>>A169RES          \",\"E      21.0 \",\"BOOL      \",\"(A169) Reserviert                                                               \"",
            "\"<<BMK>>A170RES          \",\"E      21.1 \",\"BOOL      \",\"(A170) Reserviert                                                               \"",
            "\"<<BMK>>A171RES          \",\"E      21.2 \",\"BOOL      \",\"(A171) Reserviert                                                               \"",
            "\"<<BMK>>A172RES          \",\"E      21.3 \",\"BOOL      \",\"(A172) Reserviert                                                               \"",
            "\"<<BMK>>A173RES          \",\"E      21.4 \",\"BOOL      \",\"(A173) Reserviert                                                               \"",
            "\"<<BMK>>A174RES          \",\"E      21.5 \",\"BOOL      \",\"(A174) Reserviert                                                               \"",
            "\"<<BMK>>A175RES          \",\"E      21.6 \",\"BOOL      \",\"(A175) Reserviert                                                               \"",
            "\"<<BMK>>A176RES          \",\"E      21.7 \",\"BOOL      \",\"(A176) Reserviert                                                               \"",
            "\"<<BMK>>A177RES          \",\"E      22.0 \",\"BOOL      \",\"(A177) Reserviert                                                               \"",
            "\"<<BMK>>A178RES          \",\"E      22.1 \",\"BOOL      \",\"(A178) Reserviert                                                               \"",
            "\"<<BMK>>A179RES          \",\"E      22.2 \",\"BOOL      \",\"(A179) Reserviert                                                               \"",
            "\"<<BMK>>A180RES          \",\"E      22.3 \",\"BOOL      \",\"(A180) Reserviert                                                               \"",
            "\"<<BMK>>A181RES          \",\"E      22.4 \",\"BOOL      \",\"(A181) Reserviert                                                               \"",
            "\"<<BMK>>A182RES          \",\"E      22.5 \",\"BOOL      \",\"(A182) Reserviert                                                               \"",
            "\"<<BMK>>A183RES          \",\"E      22.6 \",\"BOOL      \",\"(A183) Reserviert                                                               \"",
            "\"<<BMK>>A184RES          \",\"E      22.7 \",\"BOOL      \",\"(A184) Reserviert                                                               \"",
            "\"<<BMK>>A185RES          \",\"E      23.0 \",\"BOOL      \",\"(A185) Reserviert                                                               \"",
            "\"<<BMK>>A186RES          \",\"E      23.1 \",\"BOOL      \",\"(A186) Reserviert                                                               \"",
            "\"<<BMK>>A187RES          \",\"E      23.2 \",\"BOOL      \",\"(A187) Reserviert                                                               \"",
            "\"<<BMK>>A188RES          \",\"E      23.3 \",\"BOOL      \",\"(A188) Reserviert                                                               \"",
            "\"<<BMK>>A189RES          \",\"E      23.4 \",\"BOOL      \",\"(A189) Reserviert                                                               \"",
            "\"<<BMK>>A190RES          \",\"E      23.5 \",\"BOOL      \",\"(A190) Reserviert                                                               \"",
            "\"<<BMK>>A191RES          \",\"E      23.6 \",\"BOOL      \",\"(A191) Reserviert                                                               \"",
            "\"<<BMK>>A192RES          \",\"E      23.7 \",\"BOOL      \",\"(A192) Reserviert                                                               \"",
            "\"<<BMK>>A193RES          \",\"E      24.0 \",\"BOOL      \",\"(A193) Reserviert                                                               \"",
            "\"<<BMK>>A194RES          \",\"E      24.1 \",\"BOOL      \",\"(A194) Reserviert                                                               \"",
            "\"<<BMK>>A195RES          \",\"E      24.2 \",\"BOOL      \",\"(A195) Reserviert                                                               \"",
            "\"<<BMK>>A196RES          \",\"E      24.3 \",\"BOOL      \",\"(A196) Reserviert                                                               \"",
            "\"<<BMK>>A197RES          \",\"E      24.4 \",\"BOOL      \",\"(A197) Reserviert                                                               \"",
            "\"<<BMK>>A198RES          \",\"E      24.5 \",\"BOOL      \",\"(A198) Reserviert                                                               \"",
            "\"<<BMK>>A199RES          \",\"E      24.6 \",\"BOOL      \",\"(A199) Reserviert                                                               \"",
            "\"<<BMK>>A200RES          \",\"E      24.7 \",\"BOOL      \",\"(A200) Reserviert                                                               \"",
            "\"<<BMK>>A201RES          \",\"E      25.0 \",\"BOOL      \",\"(A201) Reserviert                                                               \"",
            "\"<<BMK>>A202RES          \",\"E      25.1 \",\"BOOL      \",\"(A202) Reserviert                                                               \"",
            "\"<<BMK>>A203RES          \",\"E      25.2 \",\"BOOL      \",\"(A203) Reserviert                                                               \"",
            "\"<<BMK>>A204RES          \",\"E      25.3 \",\"BOOL      \",\"(A204) Reserviert                                                               \"",
            "\"<<BMK>>A205RES          \",\"E      25.4 \",\"BOOL      \",\"(A205) Reserviert                                                               \"",
            "\"<<BMK>>A206RES          \",\"E      25.5 \",\"BOOL      \",\"(A206) Reserviert                                                               \"",
            "\"<<BMK>>A207RES          \",\"E      25.6 \",\"BOOL      \",\"(A207) Reserviert                                                               \"",
            "\"<<BMK>>A208RES          \",\"E      25.7 \",\"BOOL      \",\"(A208) Reserviert                                                               \"",
            "\"<<BMK>>A209RES          \",\"E      26.0 \",\"BOOL      \",\"(A209) Reserviert                                                               \"",
            "\"<<BMK>>A210RES          \",\"E      26.1 \",\"BOOL      \",\"(A210) Reserviert                                                               \"",
            "\"<<BMK>>A211RES          \",\"E      26.2 \",\"BOOL      \",\"(A211) Reserviert                                                               \"",
            "\"<<BMK>>A212RES          \",\"E      26.3 \",\"BOOL      \",\"(A212) Reserviert                                                               \"",
            "\"<<BMK>>A213RES          \",\"E      26.4 \",\"BOOL      \",\"(A213) Reserviert                                                               \"",
            "\"<<BMK>>A214RES          \",\"E      26.5 \",\"BOOL      \",\"(A214) Reserviert                                                               \"",
            "\"<<BMK>>A215RES          \",\"E      26.6 \",\"BOOL      \",\"(A215) Reserviert                                                               \"",
            "\"<<BMK>>A216RES          \",\"E      26.7 \",\"BOOL      \",\"(A216) Reserviert                                                               \"",
            "\"<<BMK>>A217RES          \",\"E      27.0 \",\"BOOL      \",\"(A217) Reserviert                                                               \"",
            "\"<<BMK>>A218RES          \",\"E      27.1 \",\"BOOL      \",\"(A218) Reserviert                                                               \"",
            "\"<<BMK>>A219RES          \",\"E      27.2 \",\"BOOL      \",\"(A219) Reserviert                                                               \"",
            "\"<<BMK>>A220RES          \",\"E      27.3 \",\"BOOL      \",\"(A220) Reserviert                                                               \"",
            "\"<<BMK>>A221RES          \",\"E      27.4 \",\"BOOL      \",\"(A221) Reserviert                                                               \"",
            "\"<<BMK>>A222RES          \",\"E      27.5 \",\"BOOL      \",\"(A222) Reserviert                                                               \"",
            "\"<<BMK>>A223RES          \",\"E      27.6 \",\"BOOL      \",\"(A223) Reserviert                                                               \"",
            "\"<<BMK>>A224RES          \",\"E      27.7 \",\"BOOL      \",\"(A224) Reserviert                                                               \"",
            "\"<<BMK>>A225RES          \",\"E      28.0 \",\"BOOL      \",\"(A225) Reserviert                                                               \"",
            "\"<<BMK>>A226RES          \",\"E      28.1 \",\"BOOL      \",\"(A226) Reserviert                                                               \"",
            "\"<<BMK>>A227RES          \",\"E      28.2 \",\"BOOL      \",\"(A227) Reserviert                                                               \"",
            "\"<<BMK>>A228RES          \",\"E      28.3 \",\"BOOL      \",\"(A228) Reserviert                                                               \"",
            "\"<<BMK>>A229RES          \",\"E      28.4 \",\"BOOL      \",\"(A229) Reserviert                                                               \"",
            "\"<<BMK>>A230RES          \",\"E      28.5 \",\"BOOL      \",\"(A230) Reserviert                                                               \"",
            "\"<<BMK>>A231RES          \",\"E      28.6 \",\"BOOL      \",\"(A231) Reserviert                                                               \"",
            "\"<<BMK>>A232RES          \",\"E      28.7 \",\"BOOL      \",\"(A232) Reserviert                                                               \"",
            "\"<<BMK>>A233RES          \",\"E      29.0 \",\"BOOL      \",\"(A233) Reserviert                                                               \"",
            "\"<<BMK>>A234RES          \",\"E      29.1 \",\"BOOL      \",\"(A234) Reserviert                                                               \"",
            "\"<<BMK>>A235RES          \",\"E      29.2 \",\"BOOL      \",\"(A235) Reserviert                                                               \"",
            "\"<<BMK>>A236RES          \",\"E      29.3 \",\"BOOL      \",\"(A236) Reserviert                                                               \"",
            "\"<<BMK>>A237RES          \",\"E      29.4 \",\"BOOL      \",\"(A237) Reserviert                                                               \"",
            "\"<<BMK>>A238RES          \",\"E      29.5 \",\"BOOL      \",\"(A238) Reserviert                                                               \"",
            "\"<<BMK>>A239RES          \",\"E      29.6 \",\"BOOL      \",\"(A239) Reserviert                                                               \"",
            "\"<<BMK>>A240RES          \",\"E      29.7 \",\"BOOL      \",\"(A240) Reserviert                                                               \"",
            "\"<<BMK>>A241RES          \",\"E      30.0 \",\"BOOL      \",\"(A241) Reserviert                                                               \"",
            "\"<<BMK>>A242RES          \",\"E      30.1 \",\"BOOL      \",\"(A242) Reserviert                                                               \"",
            "\"<<BMK>>A243RES          \",\"E      30.2 \",\"BOOL      \",\"(A243) Reserviert                                                               \"",
            "\"<<BMK>>A244RES          \",\"E      30.3 \",\"BOOL      \",\"(A244) Reserviert                                                               \"",
            "\"<<BMK>>A245RES          \",\"E      30.4 \",\"BOOL      \",\"(A245) Reserviert                                                               \"",
            "\"<<BMK>>A246RES          \",\"E      30.5 \",\"BOOL      \",\"(A246) Reserviert                                                               \"",
            "\"<<BMK>>A247RES          \",\"E      30.6 \",\"BOOL      \",\"(A247) Reserviert                                                               \"",
            "\"<<BMK>>A248RES          \",\"E      30.7 \",\"BOOL      \",\"(A248) Reserviert                                                               \"",
            "\"<<BMK>>_NHL             \",\"E      32.0 \",\"BOOL      \",\"(A0_0) Not Halt Lokal                                                           \"",
            "\"<<BMK>>_AF              \",\"E      32.1 \",\"BOOL      \",\"(A0_1) Antriebsfreigabe                                                         \"",
            "\"<<BMK>>_FF              \",\"E      32.2 \",\"BOOL      \",\"(A0_2) Fahrfreigabe                                                             \"",
            "\"<<BMK>>_ZS              \",\"E      32.3 \",\"BOOL      \",\"(A0_3) Zustimmschalter in Mittelstellung                                        \"",
            "\"<<BMK>>_OUT5            \",\"E      32.4 \",\"BOOL      \",\"(A0_4) Reserviert                                                               \"",
            "\"<<BMK>>_AUT             \",\"E      32.5 \",\"BOOL      \",\"(A0_5) Roboter in Automatik                                                     \"",
            "\"<<BMK>>_T1              \",\"E      32.6 \",\"BOOL      \",\"(A0_6) Roboter in T1                                                            \"",
            "\"<<BMK>>_T2              \",\"E      32.7 \",\"BOOL      \",\"(A0_7) Roboter in T2                                                            \"",
            "\"<<BMK>>_NHEK            \",\"E      33.0 \",\"BOOL      \",\"(A1_0) Rueckmeldung Not-Halt Extern                                             \"",
            "\"<<BMK>>_BSK             \",\"E      33.1 \",\"BOOL      \",\"(A1_1) Rueckmeldung Bedienerschutz                                              \"",
            "\"<<BMK>>_SHS1K           \",\"E      33.2 \",\"BOOL      \",\"(A1_2) Sicherheitshalt Stopp 1 erreicht                                         \"",
            "\"<<BMK>>_SHS2K           \",\"E      33.3 \",\"BOOL      \",\"(A1_3) Sicherheitshalt Stopp 2 erreicht                                         \"",
            "\"<<BMK>>_OUT13           \",\"E      33.4 \",\"BOOL      \",\"(A1_4) Reserviert                                                               \"",
            "\"<<BMK>>_OUT14           \",\"E      33.5 \",\"BOOL      \",\"(A1_5) Reserviert                                                               \"",
            "\"<<BMK>>_PSA             \",\"E      33.6 \",\"BOOL      \",\"(A1_6) Profi Safe Schnittstelle ist aktiv                                       \"",
            "\"<<BMK>>_SP              \",\"E      33.7 \",\"BOOL      \",\"(A1_7) Abmeldung der Profi Safe Verbindung                                      \"",
            "\"<<BMK>>E001FLGW1        \",\"A       0.0 \",\"BOOL      \",\"(E1) Folgenanwahl W1                                                            \"",
            "\"<<BMK>>E002FLGW2        \",\"A       0.1 \",\"BOOL      \",\"(E2) Folgenanwahl W2                                                            \"",
            "\"<<BMK>>E003FLGW4        \",\"A       0.2 \",\"BOOL      \",\"(E3) Folgenanwahl W4                                                            \"",
            "\"<<BMK>>E004FLGW8        \",\"A       0.3 \",\"BOOL      \",\"(E4) Folgenanwahl W8                                                            \"",
            "\"<<BMK>>E005FLGW16       \",\"A       0.4 \",\"BOOL      \",\"(E5) Folgenanwahl W16                                                           \"",
            "\"<<BMK>>E006FLGW32       \",\"A       0.5 \",\"BOOL      \",\"(E6) Folgenanwahl W32                                                           \"",
            "\"<<BMK>>E007FLGW64       \",\"A       0.6 \",\"BOOL      \",\"(E7) Folgenanwahl W64                                                           \"",
            "\"<<BMK>>E008FLGW128      \",\"A       0.7 \",\"BOOL      \",\"(E8) Folgenanwahl W128                                                          \"",
            "\"<<BMK>>E009SRB          \",\"A       1.0 \",\"BOOL      \",\"(E9) Folgestart                                                                 \"",
            "\"<<BMK>>E010ANTR         \",\"A       1.1 \",\"BOOL      \",\"(E10) Antriebe Ein                                                              \"",
            "\"<<BMK>>E011K25          \",\"A       1.2 \",\"BOOL      \",\"(E11) Anlage ist in Hand (K25)                                                  \"",
            "\"<<BMK>>E012K26          \",\"A       1.3 \",\"BOOL      \",\"(E12) Anlage ist in Automatik (K26)                                             \"",
            "\"<<BMK>>E013K36          \",\"A       1.4 \",\"BOOL      \",\"(E13) Schutzkreis ist geschlossen                                               \"",
            "\"<<BMK>>E014MSICH        \",\"A       1.5 \",\"BOOL      \",\"(E14) Maschinelle Sicherheiten                                                  \"",
            "\"<<BMK>>E015POT          \",\"A       1.6 \",\"BOOL      \",\"(E15) Funktionstest ohne Bauteil                                                \"",
            "\"<<BMK>>E016HALTKO       \",\"A       1.7 \",\"BOOL      \",\"(E16) Halt zum Korrigieren                                                      \"",
            "\"<<BMK>>E017FRW1         \",\"A       2.0 \",\"BOOL      \",\"(E17) Quittierung Wartungsstellung                                              \"",
            "\"<<BMK>>E018HALTWART     \",\"A       2.1 \",\"BOOL      \",\"(E18) Halt in Wartungsbereich                                                   \"",
            "\"<<BMK>>E019WART         \",\"A       2.2 \",\"BOOL      \",\"(E19) Wartung in Arbeitsfolge                                                   \"",
            "\"<<BMK>>E020AWERKW       \",\"A       2.3 \",\"BOOL      \",\"(E20) Anwahl Werkzeugwechselposition                                            \"",
            "\"<<BMK>>E021AREFPO       \",\"A       2.4 \",\"BOOL      \",\"(E21) Anwahl Referenzposition                                                   \"",
            "\"<<BMK>>E022FRGFLGW      \",\"A       2.5 \",\"BOOL      \",\"(E22) Freigabe Folgenwiederholung                                               \"",
            "\"<<BMK>>E023ZUTRITT      \",\"A       2.6 \",\"BOOL      \",\"(E23) Keine Zutrittsanforderung                                                 \"",
            "\"<<BMK>>E024MEDVOR       \",\"A       2.7 \",\"BOOL      \",\"(E24) Medien vorhanden                                                          \"",
            "\"<<BMK>>E025MEDEIN       \",\"A       3.0 \",\"BOOL      \",\"(E25) Medien einschalten                                                        \"",
            "\"<<BMK>>E026QUITWIE      \",\"A       3.1 \",\"BOOL      \",\"(E26) Quitt mit Wiederholung                                                    \"",
            "\"<<BMK>>E027QUITWEI      \",\"A       3.2 \",\"BOOL      \",\"(E27) Quitt Weiter                                                              \"",
            "\"<<BMK>>E028QUITAUSS     \",\"A       3.3 \",\"BOOL      \",\"(E28) Quitt mit Teil ausschleusen                                               \"",
            "\"<<BMK>>E029ANFENERGI    \",\"A       3.4 \",\"BOOL      \",\"(E29) Anforderung Energiesparmodus                                              \"",
            "\"<<BMK>>E030ANFABSCH     \",\"A       3.5 \",\"BOOL      \",\"(E30) Anforderung Abschaltung                                                   \"",
            "\"<<BMK>>E031ANFARCHIV    \",\"A       3.6 \",\"BOOL      \",\"(E31) Anforderung Archivieren                                                   \"",
            "\"<<BMK>>E032ZURUECK      \",\"A       3.7 \",\"BOOL      \",\"(E32) Rueckzug aus Vorposition                                                  \"",
            "\"<<BMK>>E033QABE_W1      \",\"A       4.0 \",\"BOOL      \",\"(E33) Quitt Arbeitsfertigmeldung W1                                             \"",
            "\"<<BMK>>E034QABE_W2      \",\"A       4.1 \",\"BOOL      \",\"(E34) Quitt Arbeitsfertigmeldung W2                                             \"",
            "\"<<BMK>>E035QABE_W4      \",\"A       4.2 \",\"BOOL      \",\"(E35) Quitt Arbeitsfertigmeldung W4                                             \"",
            "\"<<BMK>>E036QABE_W8      \",\"A       4.3 \",\"BOOL      \",\"(E36) Quitt Arbeitsfertigmeldung W8                                             \"",
            "\"<<BMK>>E037_E_TYP_W1    \",\"A       4.4 \",\"BOOL      \",\"(E37) Typinfo W1 an Roboter                                                     \"",
            "\"<<BMK>>E038_E_TYP_W2    \",\"A       4.5 \",\"BOOL      \",\"(E38) Typinfo W2 an Roboter                                                     \"",
            "\"<<BMK>>E039_E_TYP_W4    \",\"A       4.6 \",\"BOOL      \",\"(E39) Typinfo W4 an Roboter                                                     \"",
            "\"<<BMK>>E040_E_TYP_W8    \",\"A       4.7 \",\"BOOL      \",\"(E40) Typinfo W8 an Roboter                                                     \"",
            "\"<<BMK>>E041F1           \",\"A       5.0 \",\"BOOL      \",\"(E41) Roboterfreigabe 1 Rob < Rob                                               \"",
            "\"<<BMK>>E042F2           \",\"A       5.1 \",\"BOOL      \",\"(E42) Roboterfreigabe 2 Rob < Rob                                               \"",
            "\"<<BMK>>E043F3           \",\"A       5.2 \",\"BOOL      \",\"(E43) Roboterfreigabe 3 Rob < Rob                                               \"",
            "\"<<BMK>>E044F4           \",\"A       5.3 \",\"BOOL      \",\"(E44) Roboterfreigabe 4 Rob < Rob                                               \"",
            "\"<<BMK>>E045F5           \",\"A       5.4 \",\"BOOL      \",\"(E45) Roboterfreigabe 5 Rob < Rob                                               \"",
            "\"<<BMK>>E046F6           \",\"A       5.5 \",\"BOOL      \",\"(E46) Roboterfreigabe 6 Rob < Rob                                               \"",
            "\"<<BMK>>E047F7           \",\"A       5.6 \",\"BOOL      \",\"(E47) Roboterfreigabe 7 Rob < Rob                                               \"",
            "\"<<BMK>>E048F8           \",\"A       5.7 \",\"BOOL      \",\"(E48) Roboterfreigabe 8 Rob < Rob                                               \"",
            "\"<<BMK>>E049F9           \",\"A       6.0 \",\"BOOL      \",\"(E49) Roboterfreigabe 9 Rob < Rob                                               \"",
            "\"<<BMK>>E050F10          \",\"A       6.1 \",\"BOOL      \",\"(E50) Roboterfreigabe 10 Rob < Rob                                              \"",
            "\"<<BMK>>E051F11          \",\"A       6.2 \",\"BOOL      \",\"(E51) Roboterfreigabe 11 Rob < Rob                                              \"",
            "\"<<BMK>>E052F12          \",\"A       6.3 \",\"BOOL      \",\"(E52) Roboterfreigabe 12 Rob < Rob                                              \"",
            "\"<<BMK>>E053F13          \",\"A       6.4 \",\"BOOL      \",\"(E53) Roboterfreigabe 13 Rob < Rob                                              \"",
            "\"<<BMK>>E054F14          \",\"A       6.5 \",\"BOOL      \",\"(E54) Roboterfreigabe 14 Rob < Rob                                              \"",
            "\"<<BMK>>E055F15          \",\"A       6.6 \",\"BOOL      \",\"(E55) Roboterfreigabe 15 Rob < Rob                                              \"",
            "\"<<BMK>>E056F16          \",\"A       6.7 \",\"BOOL      \",\"(E56) Roboterfreigabe 16 Rob < Rob                                              \"",
            "\"<<BMK>>E057MS24         \",\"A       7.0 \",\"BOOL      \",\"(E57) Stellungsfreigabe 24 Rob < Anlage                                         \"",
            "\"<<BMK>>E058MS23         \",\"A       7.1 \",\"BOOL      \",\"(E58) Stellungsfreigabe 23 Rob < Anlage                                         \"",
            "\"<<BMK>>E059MS22         \",\"A       7.2 \",\"BOOL      \",\"(E59) Stellungsfreigabe 22 Rob < Anlage                                         \"",
            "\"<<BMK>>E060MS21         \",\"A       7.3 \",\"BOOL      \",\"(E60) Stellungsfreigabe 21 Rob < Anlage                                         \"",
            "\"<<BMK>>E061MS20         \",\"A       7.4 \",\"BOOL      \",\"(E61) Stellungsfreigabe 20 Rob < Anlage                                         \"",
            "\"<<BMK>>E062MS19         \",\"A       7.5 \",\"BOOL      \",\"(E62) Stellungsfreigabe 19 Rob < Anlage                                         \"",
            "\"<<BMK>>E063MS18         \",\"A       7.6 \",\"BOOL      \",\"(E63) Stellungsfreigabe 18 Rob < Anlage                                         \"",
            "\"<<BMK>>E064MS17         \",\"A       7.7 \",\"BOOL      \",\"(E64) Stellungsfreigabe 17 Rob < Anlage                                         \"",
            "\"<<BMK>>E065MS16         \",\"A       8.0 \",\"BOOL      \",\"(E65) Stellungsfreigabe 16 Rob < Anlage                                         \"",
            "\"<<BMK>>E066MS15         \",\"A       8.1 \",\"BOOL      \",\"(E66) Stellungsfreigabe 15 Rob < Anlage                                         \"",
            "\"<<BMK>>E067MS14         \",\"A       8.2 \",\"BOOL      \",\"(E67) Stellungsfreigabe 14 Rob < Anlage                                         \"",
            "\"<<BMK>>E068MS13         \",\"A       8.3 \",\"BOOL      \",\"(E68) Stellungsfreigabe 13 Rob < Anlage                                         \"",
            "\"<<BMK>>E069MS12         \",\"A       8.4 \",\"BOOL      \",\"(E69) Stellungsfreigabe 12 Rob < Anlage                                         \"",
            "\"<<BMK>>E070MS11         \",\"A       8.5 \",\"BOOL      \",\"(E70) Stellungsfreigabe 11 Rob < Anlage                                         \"",
            "\"<<BMK>>E071MS10         \",\"A       8.6 \",\"BOOL      \",\"(E71) Stellungsfreigabe 10 Rob < Anlage                                         \"",
            "\"<<BMK>>E072MS9          \",\"A       8.7 \",\"BOOL      \",\"(E72) Stellungsfreigabe 9 Rob < Anlage                                          \"",
            "\"<<BMK>>E073MS8          \",\"A       9.0 \",\"BOOL      \",\"(E73) Stellungsfreigabe 8 Rob < Anlage                                          \"",
            "\"<<BMK>>E074MS7          \",\"A       9.1 \",\"BOOL      \",\"(E74) Stellungsfreigabe 7 Rob < Anlage                                          \"",
            "\"<<BMK>>E075MS6          \",\"A       9.2 \",\"BOOL      \",\"(E75) Stellungsfreigabe 6 Rob < Anlage                                          \"",
            "\"<<BMK>>E076MS5          \",\"A       9.3 \",\"BOOL      \",\"(E76) Stellungsfreigabe 5 Rob < Anlage                                          \"",
            "\"<<BMK>>E077MS4          \",\"A       9.4 \",\"BOOL      \",\"(E77) Stellungsfreigabe 4 Rob < Anlage                                          \"",
            "\"<<BMK>>E078MS3          \",\"A       9.5 \",\"BOOL      \",\"(E78) Stellungsfreigabe 3 Rob < Anlage                                          \"",
            "\"<<BMK>>E079MS2          \",\"A       9.6 \",\"BOOL      \",\"(E79) Stellungsfreigabe 2 Rob < Anlage                                          \"",
            "\"<<BMK>>E080MS1          \",\"A       9.7 \",\"BOOL      \",\"(E80) Stellungsfreigabe 1 Rob < Anlage                                          \"",
            "\"<<BMK>>E081QAF_VER1     \",\"A      10.0 \",\"BOOL      \",\"(E81) Quitt. Verriegelung 1 Rob < Rob                                           \"",
            "\"<<BMK>>E082QAF_VER2     \",\"A      10.1 \",\"BOOL      \",\"(E82) Quitt. Verriegelung 2 Rob < Rob                                           \"",
            "\"<<BMK>>E083QAF_VER3     \",\"A      10.2 \",\"BOOL      \",\"(E83) Quitt. Verriegelung 3 Rob < Rob                                           \"",
            "\"<<BMK>>E084QAF_VER4     \",\"A      10.3 \",\"BOOL      \",\"(E84) Quitt. Verriegelung 4 Rob < Rob                                           \"",
            "\"<<BMK>>E085QAF_VER5     \",\"A      10.4 \",\"BOOL      \",\"(E85) Quitt. Verriegelung 5 Rob < Rob                                           \"",
            "\"<<BMK>>E086QAF_VER6     \",\"A      10.5 \",\"BOOL      \",\"(E86) Quitt. Verriegelung 6 Rob < Rob                                           \"",
            "\"<<BMK>>E087QAF_VER7     \",\"A      10.6 \",\"BOOL      \",\"(E87) Quitt. Verriegelung 7 Rob < Rob                                           \"",
            "\"<<BMK>>E088QAF_VER8     \",\"A      10.7 \",\"BOOL      \",\"(E88) Quitt. Verriegelung 8 Rob < Rob                                           \"",
            "\"<<BMK>>E089QAF_VER9     \",\"A      11.0 \",\"BOOL      \",\"(E89) Quitt. Verriegelung 9 Rob < Rob                                           \"",
            "\"<<BMK>>E090QAF_VER10    \",\"A      11.1 \",\"BOOL      \",\"(E90) Quitt. Verriegelung 10 Rob < Rob                                          \"",
            "\"<<BMK>>E091QAF_VER11    \",\"A      11.2 \",\"BOOL      \",\"(E91) Quitt. Verriegelung 11 Rob < Rob                                          \"",
            "\"<<BMK>>E092QAF_VER12    \",\"A      11.3 \",\"BOOL      \",\"(E92) Quitt. Verriegelung 12 Rob < Rob                                          \"",
            "\"<<BMK>>E093QAF_VER13    \",\"A      11.4 \",\"BOOL      \",\"(E93) Quitt. Verriegelung 13 Rob < Rob                                          \"",
            "\"<<BMK>>E094QAF_VER14    \",\"A      11.5 \",\"BOOL      \",\"(E94) Quitt. Verriegelung 14 Rob < Rob                                          \"",
            "\"<<BMK>>E095QAF_VER15    \",\"A      11.6 \",\"BOOL      \",\"(E95) Quitt. Verriegelung 15 Rob < Rob                                          \"",
            "\"<<BMK>>E096QAF_VER16    \",\"A      11.7 \",\"BOOL      \",\"(E96) Quitt. Verriegelung 16 Rob < Rob                                          \"",
            "\"<<BMK>>E097RES          \",\"A      12.0 \",\"BOOL      \",\"(E97) Reserviert                                                                \"",
            "\"<<BMK>>E098RES          \",\"A      12.1 \",\"BOOL      \",\"(E98) Reserviert                                                                \"",
            "\"<<BMK>>E099RES          \",\"A      12.2 \",\"BOOL      \",\"(E99) Reserviert                                                                \"",
            "\"<<BMK>>E100RES          \",\"A      12.3 \",\"BOOL      \",\"(E100) Reserviert                                                               \"",
            "\"<<BMK>>E101RES          \",\"A      12.4 \",\"BOOL      \",\"(E101) Reserviert                                                               \"",
            "\"<<BMK>>E102RES          \",\"A      12.5 \",\"BOOL      \",\"(E102) Reserviert                                                               \"",
            "\"<<BMK>>E103RES          \",\"A      12.6 \",\"BOOL      \",\"(E103) Reserviert                                                               \"",
            "\"<<BMK>>E104RES          \",\"A      12.7 \",\"BOOL      \",\"(E104) Reserviert                                                               \"",
            "\"<<BMK>>E105RES          \",\"A      13.0 \",\"BOOL      \",\"(E105) Reserviert                                                               \"",
            "\"<<BMK>>E106RES          \",\"A      13.1 \",\"BOOL      \",\"(E106) Reserviert                                                               \"",
            "\"<<BMK>>E107RES          \",\"A      13.2 \",\"BOOL      \",\"(E107) Reserviert                                                               \"",
            "\"<<BMK>>E108RES          \",\"A      13.3 \",\"BOOL      \",\"(E108) Reserviert                                                               \"",
            "\"<<BMK>>E109RES          \",\"A      13.4 \",\"BOOL      \",\"(E109) Reserviert                                                               \"",
            "\"<<BMK>>E110RES          \",\"A      13.5 \",\"BOOL      \",\"(E110) Reserviert                                                               \"",
            "\"<<BMK>>E111RES          \",\"A      13.6 \",\"BOOL      \",\"(E111) Reserviert                                                               \"",
            "\"<<BMK>>E112RES          \",\"A      13.7 \",\"BOOL      \",\"(E112) Reserviert                                                               \"",
            "\"<<BMK>>E113RES          \",\"A      14.0 \",\"BOOL      \",\"(E113) Reserviert                                                               \"",
            "\"<<BMK>>E114RES          \",\"A      14.1 \",\"BOOL      \",\"(E114) Reserviert                                                               \"",
            "\"<<BMK>>E115RES          \",\"A      14.2 \",\"BOOL      \",\"(E115) Reserviert                                                               \"",
            "\"<<BMK>>E116RES          \",\"A      14.3 \",\"BOOL      \",\"(E116) Reserviert                                                               \"",
            "\"<<BMK>>E117RES          \",\"A      14.4 \",\"BOOL      \",\"(E117) Reserviert                                                               \"",
            "\"<<BMK>>E118RES          \",\"A      14.5 \",\"BOOL      \",\"(E118) Reserviert                                                               \"",
            "\"<<BMK>>E119RES          \",\"A      14.6 \",\"BOOL      \",\"(E119) Reserviert                                                               \"",
            "\"<<BMK>>E120RES          \",\"A      14.7 \",\"BOOL      \",\"(E120) Reserviert                                                               \"",
            "\"<<BMK>>E121RES          \",\"A      15.0 \",\"BOOL      \",\"(E121) Reserviert                                                               \"",
            "\"<<BMK>>E122RES          \",\"A      15.1 \",\"BOOL      \",\"(E122) Reserviert                                                               \"",
            "\"<<BMK>>E123RES          \",\"A      15.2 \",\"BOOL      \",\"(E123) Reserviert                                                               \"",
            "\"<<BMK>>E124RES          \",\"A      15.3 \",\"BOOL      \",\"(E124) Reserviert                                                               \"",
            "\"<<BMK>>E125RES          \",\"A      15.4 \",\"BOOL      \",\"(E125) Reserviert                                                               \"",
            "\"<<BMK>>E126RES          \",\"A      15.5 \",\"BOOL      \",\"(E126) Reserviert                                                               \"",
            "\"<<BMK>>E127RES          \",\"A      15.6 \",\"BOOL      \",\"(E127) Reserviert                                                               \"",
            "\"<<BMK>>E128RES          \",\"A      15.7 \",\"BOOL      \",\"(E128) Reserviert                                                               \"",
            "\"<<BMK>>E129RES          \",\"A      16.0 \",\"BOOL      \",\"(E129) Reserviert                                                               \"",
            "\"<<BMK>>E130RES          \",\"A      16.1 \",\"BOOL      \",\"(E130) Reserviert                                                               \"",
            "\"<<BMK>>E131RES          \",\"A      16.2 \",\"BOOL      \",\"(E131) Reserviert                                                               \"",
            "\"<<BMK>>E132RES          \",\"A      16.3 \",\"BOOL      \",\"(E132) Reserviert                                                               \"",
            "\"<<BMK>>E133RES          \",\"A      16.4 \",\"BOOL      \",\"(E133) Reserviert                                                               \"",
            "\"<<BMK>>E134RES          \",\"A      16.5 \",\"BOOL      \",\"(E134) Reserviert                                                               \"",
            "\"<<BMK>>E135RES          \",\"A      16.6 \",\"BOOL      \",\"(E135) Reserviert                                                               \"",
            "\"<<BMK>>E136RES          \",\"A      16.7 \",\"BOOL      \",\"(E136) Reserviert                                                               \"",
            "\"<<BMK>>E137RES          \",\"A      17.0 \",\"BOOL      \",\"(E137) Reserviert                                                               \"",
            "\"<<BMK>>E138RES          \",\"A      17.1 \",\"BOOL      \",\"(E138) Reserviert                                                               \"",
            "\"<<BMK>>E139RES          \",\"A      17.2 \",\"BOOL      \",\"(E139) Reserviert                                                               \"",
            "\"<<BMK>>E140RES          \",\"A      17.3 \",\"BOOL      \",\"(E140) Reserviert                                                               \"",
            "\"<<BMK>>E141RES          \",\"A      17.4 \",\"BOOL      \",\"(E141) Reserviert                                                               \"",
            "\"<<BMK>>E142RES          \",\"A      17.5 \",\"BOOL      \",\"(E142) Reserviert                                                               \"",
            "\"<<BMK>>E143RES          \",\"A      17.6 \",\"BOOL      \",\"(E143) Reserviert                                                               \"",
            "\"<<BMK>>E144RES          \",\"A      17.7 \",\"BOOL      \",\"(E144) Reserviert                                                               \"",
            "\"<<BMK>>E145RES          \",\"A      18.0 \",\"BOOL      \",\"(E145) Reserviert                                                               \"",
            "\"<<BMK>>E146RES          \",\"A      18.1 \",\"BOOL      \",\"(E146) Reserviert                                                               \"",
            "\"<<BMK>>E147RES          \",\"A      18.2 \",\"BOOL      \",\"(E147) Reserviert                                                               \"",
            "\"<<BMK>>E148RES          \",\"A      18.3 \",\"BOOL      \",\"(E148) Reserviert                                                               \"",
            "\"<<BMK>>E149RES          \",\"A      18.4 \",\"BOOL      \",\"(E149) Reserviert                                                               \"",
            "\"<<BMK>>E150RES          \",\"A      18.5 \",\"BOOL      \",\"(E150) Reserviert                                                               \"",
            "\"<<BMK>>E151RES          \",\"A      18.6 \",\"BOOL      \",\"(E151) Reserviert                                                               \"",
            "\"<<BMK>>E152RES          \",\"A      18.7 \",\"BOOL      \",\"(E152) Reserviert                                                               \"",
            "\"<<BMK>>E153RES          \",\"A      19.0 \",\"BOOL      \",\"(E153) Reserviert                                                               \"",
            "\"<<BMK>>E154RES          \",\"A      19.1 \",\"BOOL      \",\"(E154) Reserviert                                                               \"",
            "\"<<BMK>>E155RES          \",\"A      19.2 \",\"BOOL      \",\"(E155) Reserviert                                                               \"",
            "\"<<BMK>>E156RES          \",\"A      19.3 \",\"BOOL      \",\"(E156) Reserviert                                                               \"",
            "\"<<BMK>>E157RES          \",\"A      19.4 \",\"BOOL      \",\"(E157) Reserviert                                                               \"",
            "\"<<BMK>>E158RES          \",\"A      19.5 \",\"BOOL      \",\"(E158) Reserviert                                                               \"",
            "\"<<BMK>>E159RES          \",\"A      19.6 \",\"BOOL      \",\"(E159) Reserviert                                                               \"",
            "\"<<BMK>>E160RES          \",\"A      19.7 \",\"BOOL      \",\"(E160) Reserviert                                                               \"",
            "\"<<BMK>>E161RES          \",\"A      20.0 \",\"BOOL      \",\"(E161) Reserviert                                                               \"",
            "\"<<BMK>>E162RES          \",\"A      20.1 \",\"BOOL      \",\"(E162) Reserviert                                                               \"",
            "\"<<BMK>>E163RES          \",\"A      20.2 \",\"BOOL      \",\"(E163) Reserviert                                                               \"",
            "\"<<BMK>>E164RES          \",\"A      20.3 \",\"BOOL      \",\"(E164) Reserviert                                                               \"",
            "\"<<BMK>>E165RES          \",\"A      20.4 \",\"BOOL      \",\"(E165) Reserviert                                                               \"",
            "\"<<BMK>>E166RES          \",\"A      20.5 \",\"BOOL      \",\"(E166) Reserviert                                                               \"",
            "\"<<BMK>>E167RES          \",\"A      20.6 \",\"BOOL      \",\"(E167) Reserviert                                                               \"",
            "\"<<BMK>>E168RES          \",\"A      20.7 \",\"BOOL      \",\"(E168) Reserviert                                                               \"",
            "\"<<BMK>>E169RES          \",\"A      21.0 \",\"BOOL      \",\"(E169) Reserviert                                                               \"",
            "\"<<BMK>>E170RES          \",\"A      21.1 \",\"BOOL      \",\"(E170) Reserviert                                                               \"",
            "\"<<BMK>>E171RES          \",\"A      21.2 \",\"BOOL      \",\"(E171) Reserviert                                                               \"",
            "\"<<BMK>>E172RES          \",\"A      21.3 \",\"BOOL      \",\"(E172) Reserviert                                                               \"",
            "\"<<BMK>>E173RES          \",\"A      21.4 \",\"BOOL      \",\"(E173) Reserviert                                                               \"",
            "\"<<BMK>>E174RES          \",\"A      21.5 \",\"BOOL      \",\"(E174) Reserviert                                                               \"",
            "\"<<BMK>>E175RES          \",\"A      21.6 \",\"BOOL      \",\"(E175) Reserviert                                                               \"",
            "\"<<BMK>>E176RES          \",\"A      21.7 \",\"BOOL      \",\"(E176) Reserviert                                                               \"",
            "\"<<BMK>>E177RES          \",\"A      22.0 \",\"BOOL      \",\"(E177) Reserviert                                                               \"",
            "\"<<BMK>>E178RES          \",\"A      22.1 \",\"BOOL      \",\"(E178) Reserviert                                                               \"",
            "\"<<BMK>>E179RES          \",\"A      22.2 \",\"BOOL      \",\"(E179) Reserviert                                                               \"",
            "\"<<BMK>>E180RES          \",\"A      22.3 \",\"BOOL      \",\"(E180) Reserviert                                                               \"",
            "\"<<BMK>>E181RES          \",\"A      22.4 \",\"BOOL      \",\"(E181) Reserviert                                                               \"",
            "\"<<BMK>>E182RES          \",\"A      22.5 \",\"BOOL      \",\"(E182) Reserviert                                                               \"",
            "\"<<BMK>>E183RES          \",\"A      22.6 \",\"BOOL      \",\"(E183) Reserviert                                                               \"",
            "\"<<BMK>>E184RES          \",\"A      22.7 \",\"BOOL      \",\"(E184) Reserviert                                                               \"",
            "\"<<BMK>>E185RES          \",\"A      23.0 \",\"BOOL      \",\"(E185) Reserviert                                                               \"",
            "\"<<BMK>>E186RES          \",\"A      23.1 \",\"BOOL      \",\"(E186) Reserviert                                                               \"",
            "\"<<BMK>>E187RES          \",\"A      23.2 \",\"BOOL      \",\"(E187) Reserviert                                                               \"",
            "\"<<BMK>>E188RES          \",\"A      23.3 \",\"BOOL      \",\"(E188) Reserviert                                                               \"",
            "\"<<BMK>>E189RES          \",\"A      23.4 \",\"BOOL      \",\"(E189) Reserviert                                                               \"",
            "\"<<BMK>>E190RES          \",\"A      23.5 \",\"BOOL      \",\"(E190) Reserviert                                                               \"",
            "\"<<BMK>>E191RES          \",\"A      23.6 \",\"BOOL      \",\"(E191) Reserviert                                                               \"",
            "\"<<BMK>>E192RES          \",\"A      23.7 \",\"BOOL      \",\"(E192) Reserviert                                                               \"",
            "\"<<BMK>>E193RES          \",\"A      24.0 \",\"BOOL      \",\"(E193) Reserviert                                                               \"",
            "\"<<BMK>>E194RES          \",\"A      24.1 \",\"BOOL      \",\"(E194) Reserviert                                                               \"",
            "\"<<BMK>>E195RES          \",\"A      24.2 \",\"BOOL      \",\"(E195) Reserviert                                                               \"",
            "\"<<BMK>>E196RES          \",\"A      24.3 \",\"BOOL      \",\"(E196) Reserviert                                                               \"",
            "\"<<BMK>>E197RES          \",\"A      24.4 \",\"BOOL      \",\"(E197) Reserviert                                                               \"",
            "\"<<BMK>>E198RES          \",\"A      24.5 \",\"BOOL      \",\"(E198) Reserviert                                                               \"",
            "\"<<BMK>>E199RES          \",\"A      24.6 \",\"BOOL      \",\"(E199) Reserviert                                                               \"",
            "\"<<BMK>>E200RES          \",\"A      24.7 \",\"BOOL      \",\"(E200) Reserviert                                                               \"",
            "\"<<BMK>>E201RES          \",\"A      25.0 \",\"BOOL      \",\"(E201) Reserviert                                                               \"",
            "\"<<BMK>>E202RES          \",\"A      25.1 \",\"BOOL      \",\"(E202) Reserviert                                                               \"",
            "\"<<BMK>>E203RES          \",\"A      25.2 \",\"BOOL      \",\"(E203) Reserviert                                                               \"",
            "\"<<BMK>>E204RES          \",\"A      25.3 \",\"BOOL      \",\"(E204) Reserviert                                                               \"",
            "\"<<BMK>>E205RES          \",\"A      25.4 \",\"BOOL      \",\"(E205) Reserviert                                                               \"",
            "\"<<BMK>>E206RES          \",\"A      25.5 \",\"BOOL      \",\"(E206) Reserviert                                                               \"",
            "\"<<BMK>>E207RES          \",\"A      25.6 \",\"BOOL      \",\"(E207) Reserviert                                                               \"",
            "\"<<BMK>>E208RES          \",\"A      25.7 \",\"BOOL      \",\"(E208) Reserviert                                                               \"",
            "\"<<BMK>>E209RES          \",\"A      26.0 \",\"BOOL      \",\"(E209) Reserviert                                                               \"",
            "\"<<BMK>>E210RES          \",\"A      26.1 \",\"BOOL      \",\"(E210) Reserviert                                                               \"",
            "\"<<BMK>>E211RES          \",\"A      26.2 \",\"BOOL      \",\"(E211) Reserviert                                                               \"",
            "\"<<BMK>>E212RES          \",\"A      26.3 \",\"BOOL      \",\"(E212) Reserviert                                                               \"",
            "\"<<BMK>>E213RES          \",\"A      26.4 \",\"BOOL      \",\"(E213) Reserviert                                                               \"",
            "\"<<BMK>>E214RES          \",\"A      26.5 \",\"BOOL      \",\"(E214) Reserviert                                                               \"",
            "\"<<BMK>>E215RES          \",\"A      26.6 \",\"BOOL      \",\"(E215) Reserviert                                                               \"",
            "\"<<BMK>>E216RES          \",\"A      26.7 \",\"BOOL      \",\"(E216) Reserviert                                                               \"",
            "\"<<BMK>>E217RES          \",\"A      27.0 \",\"BOOL      \",\"(E217) Reserviert                                                               \"",
            "\"<<BMK>>E218RES          \",\"A      27.1 \",\"BOOL      \",\"(E218) Reserviert                                                               \"",
            "\"<<BMK>>E219RES          \",\"A      27.2 \",\"BOOL      \",\"(E219) Reserviert                                                               \"",
            "\"<<BMK>>E220RES          \",\"A      27.3 \",\"BOOL      \",\"(E220) Reserviert                                                               \"",
            "\"<<BMK>>E221RES          \",\"A      27.4 \",\"BOOL      \",\"(E221) Reserviert                                                               \"",
            "\"<<BMK>>E222RES          \",\"A      27.5 \",\"BOOL      \",\"(E222) Reserviert                                                               \"",
            "\"<<BMK>>E223RES          \",\"A      27.6 \",\"BOOL      \",\"(E223) Reserviert                                                               \"",
            "\"<<BMK>>E224RES          \",\"A      27.7 \",\"BOOL      \",\"(E224) Reserviert                                                               \"",
            "\"<<BMK>>E225RES          \",\"A      28.0 \",\"BOOL      \",\"(E225) Reserviert                                                               \"",
            "\"<<BMK>>E226RES          \",\"A      28.1 \",\"BOOL      \",\"(E226) Reserviert                                                               \"",
            "\"<<BMK>>E227RES          \",\"A      28.2 \",\"BOOL      \",\"(E227) Reserviert                                                               \"",
            "\"<<BMK>>E228RES          \",\"A      28.3 \",\"BOOL      \",\"(E228) Reserviert                                                               \"",
            "\"<<BMK>>E229RES          \",\"A      28.4 \",\"BOOL      \",\"(E229) Reserviert                                                               \"",
            "\"<<BMK>>E230RES          \",\"A      28.5 \",\"BOOL      \",\"(E230) Reserviert                                                               \"",
            "\"<<BMK>>E231RES          \",\"A      28.6 \",\"BOOL      \",\"(E231) Reserviert                                                               \"",
            "\"<<BMK>>E232RES          \",\"A      28.7 \",\"BOOL      \",\"(E232) Reserviert                                                               \"",
            "\"<<BMK>>E233RES          \",\"A      29.0 \",\"BOOL      \",\"(E233) Reserviert                                                               \"",
            "\"<<BMK>>E234RES          \",\"A      29.1 \",\"BOOL      \",\"(E234) Reserviert                                                               \"",
            "\"<<BMK>>E235RES          \",\"A      29.2 \",\"BOOL      \",\"(E235) Reserviert                                                               \"",
            "\"<<BMK>>E236RES          \",\"A      29.3 \",\"BOOL      \",\"(E236) Reserviert                                                               \"",
            "\"<<BMK>>E237RES          \",\"A      29.4 \",\"BOOL      \",\"(E237) Reserviert                                                               \"",
            "\"<<BMK>>E238RES          \",\"A      29.5 \",\"BOOL      \",\"(E238) Reserviert                                                               \"",
            "\"<<BMK>>E239RES          \",\"A      29.6 \",\"BOOL      \",\"(E239) Reserviert                                                               \"",
            "\"<<BMK>>E240RES          \",\"A      29.7 \",\"BOOL      \",\"(E240) Reserviert                                                               \"",
            "\"<<BMK>>E241RES          \",\"A      30.0 \",\"BOOL      \",\"(E241) Reserviert                                                               \"",
            "\"<<BMK>>E242RES          \",\"A      30.1 \",\"BOOL      \",\"(E242) Reserviert                                                               \"",
            "\"<<BMK>>E243RES          \",\"A      30.2 \",\"BOOL      \",\"(E243) Reserviert                                                               \"",
            "\"<<BMK>>E244RES          \",\"A      30.3 \",\"BOOL      \",\"(E244) Reserviert                                                               \"",
            "\"<<BMK>>E245RES          \",\"A      30.4 \",\"BOOL      \",\"(E245) Reserviert                                                               \"",
            "\"<<BMK>>E246RES          \",\"A      30.5 \",\"BOOL      \",\"(E246) Reserviert                                                               \"",
            "\"<<BMK>>E247RES          \",\"A      30.6 \",\"BOOL      \",\"(E247) Reserviert                                                               \"",
            "\"<<BMK>>E248RES          \",\"A      30.7 \",\"BOOL      \",\"(E248) Reserviert                                                               \"",
            "\"<<BMK>>_IN1             \",\"A      32.0 \",\"BOOL      \",\"(E0_0) Reserviert                                                               \"",
            "\"<<BMK>>_NHE             \",\"A      32.1 \",\"BOOL      \",\"(E0_1) Not Halt Extern                                                          \"",
            "\"<<BMK>>_BS              \",\"A      32.2 \",\"BOOL      \",\"(E0_2) Bedienerschutz                                                           \"",
            "\"<<BMK>>_QBS             \",\"A      32.3 \",\"BOOL      \",\"(E0_3) Quitt. Bedienerschutz                                                    \"",
            "\"<<BMK>>_SHS1            \",\"A      32.4 \",\"BOOL      \",\"(E0_4) Sicherheitshalt Stopp 1                                                  \"",
            "\"<<BMK>>_SHS2            \",\"A      32.5 \",\"BOOL      \",\"(E0_5) Sicherheitshalt Stopp 2                                                  \"",
            "\"<<BMK>>_E2              \",\"A      32.6 \",\"BOOL      \",\"(E0_6) E2 Ueberbrueckung Bedienerschutz                                         \"",
            "\"<<BMK>>_E7              \",\"A      32.7 \",\"BOOL      \",\"(E0_7) E7 Anwahl Prozessgeschwindigkeit                                         \"",
            "\"<<BMK>>_US2             \",\"A      33.0 \",\"BOOL      \",\"(E1_0) US2 Versorgungsspannung                                                  \"",
            "\"<<BMK>>_SBH             \",\"A      33.1 \",\"BOOL      \",\"(E1_1) Sicherer Betriebshalt                                                    \"",
            "\"<<BMK>>_IN11            \",\"A      33.2 \",\"BOOL      \",\"(E1_2) Reserviert                                                               \"",
            "\"<<BMK>>_IN12            \",\"A      33.3 \",\"BOOL      \",\"(E1_3) Reserviert                                                               \"",
            "\"<<BMK>>_IN13            \",\"A      33.4 \",\"BOOL      \",\"(E1_4) Reserviert                                                               \"",
            "\"<<BMK>>_IN14            \",\"A      33.5 \",\"BOOL      \",\"(E1_5) Reserviert                                                               \"",
            "\"<<BMK>>_IN15            \",\"A      33.6 \",\"BOOL      \",\"(E1_6) Reserviert                                                               \"",
            "\"<<BMK>>_SPA             \",\"A      33.7 \",\"BOOL      \",\"(E1_7) Profi Safe ist abgemeldet                                                \""
    };

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("请输入 设备名称: ");
        String name = scanner.next();
        System.out.print("请输入 起始地址: ");
        int addr = scanner.nextInt();

        try {
            FileWriter writer = new FileWriter(name + ".sdf");
            for (String line : LINES) {
                String[] ss = line.split(",");
                if (ss.length == 4) {
                    boolean A = ss[1].startsWith("\"A");
                    String address = ss[1].replace("\"", "").replace("A", "").replace("E", "").trim();
                    float f = Float.parseFloat(address);
                    f += addr;
                    line = ss[0] + (A ? ",\"A       " : ",\"E       ") + String.format("%.1f", f) + " \"," + ss[2] + "," + ss[3] + "\n";
                    line = line.replace("<<BMK>>", name);
                    System.out.print(line);
                    writer.write(line);
                }
            }
            writer.flush();
            writer.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
